#!/usr/bin/env python

import sys

# Mandatory waf variables
APPNAME = 'cc_client'   # Package name for waf dist
VERSION = '0.7.0'       # Package version for waf dist

top     = '.'           # Source directory
out     = 'build'       # Build directory

def options(opt):
    opt.load('compiler_c python')
    opt.add_option('--debug', action='store_true', default=False, help='enable debug build')

def configure(conf):
    conf.load('gnu_dirs compiler_c python')
    conf.check_python_version(minver=(2,7))

    conf.env.VERSION = VERSION
    conf.env.CFLAGS += ['-Wall', '-Wextra', '-std=gnu99']
    conf.env.LIB = ['pthread']

    conf.env.INCLUDES_CC = ['../lib/src']

    if conf.options.debug:
        conf.define('DEBUG',1)
        conf.env.CFLAGS += ['-O0', '-g']
    else:
        conf.env.CFLAGS += ['-O3']

def build(bld):
    includedir = '${PREFIX}/include/cc'
    bld.install_files(includedir, bld.path.ant_glob('src/cc_client.h'))
    bld(features='py', source=bld.path.ant_glob('src/cc_client.py'), install_from='src')

    bld(source="cc_client.pc.in")

    source_files = bld.path.ant_glob('src/*.c')
    bld.shlib(source=source_files, target=APPNAME, use='CC CCLIB JANSSON')
