#!/usr/bin/env python

# Mandatory waf variables
APPNAME = 'controlchaind'   # Package name for waf dist
VERSION = '0.0.0'           # Package version for waf dist

top     = '.'           # Source directory
out     = 'build'       # Build directory

def options(opt):
    opt.load('compiler_c')
    opt.add_option('--debug', action='store_true', default=False, help='enable debug build')

def configure(conf):
    conf.load('gnu_dirs compiler_c')

    conf.check_cfg(package='controlchain', args='--cflags --libs', uselib_store='CONTROLCHAIN',
        mandatory=True)

    conf.check_cfg(package='jansson', args='--cflags --libs', uselib_store='JANSSON',
        mandatory=True)

    conf.env.VERSION = VERSION
    conf.env.CFLAGS = ['-Wall', '-Wextra', '-std=gnu99']
    conf.env.LIB = ['pthread']

    if conf.options.debug:
        conf.define('DEBUG',1)
        conf.env.CFLAGS += ['-O0', '-g']
    else:
        conf.env.CFLAGS += ['-O3']

def build(bld):
    source_files = bld.path.ant_glob('src/*.c')
    bld.program(source=source_files, target=APPNAME, use='CONTROLCHAIN JANSSON')
