#!/usr/bin/env python

SERVER_NAME = 'controlchaind'
SERVER_VERSION = '0.6.0'

# Mandatory waf variables
# Package name and version for waf dist
APPNAME = SERVER_NAME
VERSION = SERVER_VERSION

# Source and build directories
top     = '.'
out     = 'build'

def options(opt):
    opt.load('compiler_c')
    opt.add_option('--debug', action='store_true', default=False, help='enable debug build')

def configure(conf):
    conf.load('gnu_dirs compiler_c')

    conf.env.VERSION = VERSION
    conf.env.CFLAGS += ['-Wall', '-Wextra', '-std=gnu99']
    conf.env.LIB = ['pthread']

    conf.env.INCLUDES_CC = ['../lib/src']

    if conf.options.debug:
        conf.define('DEBUG',1)
        conf.env.CFLAGS += ['-O0', '-g']
    else:
        conf.env.CFLAGS += ['-O3']

    conf.define('SERVER_NAME', SERVER_NAME)
    conf.define('SERVER_VERSION', SERVER_VERSION)
    conf.write_config_header('config.h')

def build(bld):
    source_files = bld.path.ant_glob('src/*.c')
    bld.program(source=source_files, target=APPNAME, includes='.', use='CC CCLIB JANSSON')
