#!/usr/bin/env python

# Mandatory waf variables
APPNAME = 'controlchain'    # Package name for waf dist
VERSION = '0.7.0'           # Package version for waf dist

top     = '.'           # Source directory
out     = 'build'       # Build directory

def options(opt):
    opt.load('compiler_c')
    opt.add_option('--debug', action='store_true', default=False, help='enable debug build')

def configure(conf):
    conf.load('gnu_dirs compiler_c')

    conf.check_cfg(package='libserialport', args='--cflags --libs', uselib_store='SERIALPORT',
        mandatory=True)

    conf.check_cfg(package='jansson', args='--cflags --libs', uselib_store='JANSSON',
        atleast_version='2.7', msg="Checking for 'jansson 2.7'", mandatory=True)

    conf.env.VERSION = VERSION
    conf.env.CFLAGS += ['-Wall', '-Wextra', '-std=gnu99']
    conf.env.LIB = ['pthread']

    if conf.options.debug:
        conf.define('DEBUG',1)
        conf.env.CFLAGS += ['-O0', '-g']
    else:
        conf.env.CFLAGS += ['-O3']

def build(bld):
    includedir = '${PREFIX}/include/cc'
    bld.install_files(includedir, bld.path.ant_glob('src/*.h'))

    bld(source="controlchain.pc.in")

    source_files = bld.path.ant_glob('src/*.c')
    bld.shlib(source=source_files, target=APPNAME, use='SERIALPORT JANSSON', name='CCLIB')
